apiVersion: v1
kind: Namespace
metadata:
  name: skupper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: skupper-vanform
    application: skupper-vanform
  name: skupper-vanform
  namespace: skupper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application: skupper-vanform
  name: skupper-vanform
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - skupper.io
  resources:
  - sites
  - sites/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - skupper.io
  resources:
  - links
  - links/status
  - certificates
  - certificates/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    application: skupper-vanform
  name: skupper-vanform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skupper-vanform
subjects:
- kind: ServiceAccount
  name: skupper-vanform
  namespace: skupper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-vanform
  namespace: skupper
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skupper-vanform
  template:
    metadata:
      labels:
        app.kubernetes.io/name: skupper-vanform
        app.kubernetes.io/part-of: skupper-vanform
        application: skupper-vanform
        skupper.io/component: vanform
    spec:
      containers:
      - command:
        - /app/vanform
        image: quay.io/fgiorgetti/vanform:main
        imagePullPolicy: Always
        name: vanform
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: skupper-vanform
